name: Auto-create new tag
description: "Create new tag and push to the repo"
branding:
  icon: "tag"
  color: "orange"

runs:
  using: composite
  steps:
    - name: 🏗 install autotag
      run: curl -sL https://git.io/autotag-install | sudo sh -s -- -b /usr/bin
      shell: bash

    - name: ⬆️ Increment version
      run: autotag
      shell: bash

    - name: ⤴️ Push new tag
      run: git push --tags
      shell: bash
